### ISSUE TITLE
Extra '*/' in minified version

### ISSUE THREAD

**Issue by thoughtless** [Upstatement/jquery-total-storage#2]
There seems to be an extra `*/` in the minified version. See this line: 
https://github.com/jarednova/jquery-total-storage/blob/master/jquery.total-storage.min.js#L18

I was getting weird errors after requiring loading this file in chrome. Removing that line fixed it.

**Comment by jarednova** [comment]
fixed, thanks!

On Mon, Oct 29, 2012 at 2:14 AM, Paul Cortens notifications@github.comwrote:

> There seems to be an extra */ in the minified version. See this line:
> 
> https://github.com/jarednova/jquery-total-storage/blob/master/jquery.total-storage.min.js#L18
> 
> I was getting weird errors after requiring loading this file in chrome.
> Removing that line fixed it.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jarednova/jquery-total-storage/issues/2.

## 

Partner, Upstatement
office: 617 329 1316
cell: 314 368 0228
